import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import { ServiceType } from "@prisma/client";

export interface CartItem {
  id: string; // Unique ID for the cart item (generated by uuid or crypto.randomUUID)
  serviceOfferingId: string;
  type: ServiceType;
  title: string;
  basePriceIdr: number;
  originalPriceIdr?: number | null;
  baseCurrency: "IDR" | "SAR" | "USD";
  priceInBaseCurrency: number;
  quantity: number;
  scheduledStart: Date;
  scheduledEnd?: Date;
  locationId?: string; // To track where this service happens (for cross-selling)
  metadata?: Record<string, unknown>; // Extra info like pickup location, vehicle type
}

interface CartState {
  items: CartItem[];
  addItem: (item: Omit<CartItem, "id">) => void;
  removeItem: (id: string) => void;
  updateItem: (id: string, data: Partial<CartItem>) => void;
  updateQuantity: (id: string, quantity: number) => void;
  clearCart: () => void;
  getPrimaryLocationId: () => string | undefined;
  getPrimaryDate: () => Date | undefined;
  getTotalIdr: () => number;
}

export const useCartStore = create<CartState>()(
  persist(
    (set, get) => ({
      items: [],

      addItem: (item) =>
        set((state) => {
          // Check if same service with same date is already in cart, then increment quantity
          const existingItemIndex = state.items.findIndex(
            (i) => i.serviceOfferingId === item.serviceOfferingId && i.scheduledStart.getTime() === item.scheduledStart.getTime()
          );

          if (existingItemIndex > -1) {
            const newItems = [...state.items];
            newItems[existingItemIndex].quantity += item.quantity;
            return { items: newItems };
          }

          return { items: [...state.items, { ...item, id: crypto.randomUUID() }] };
        }),

      removeItem: (id) =>
        set((state) => ({
          items: state.items.filter((item) => item.id !== id),
        })),

      updateItem: (id, data) =>
        set((state) => ({
          items: state.items.map((item) =>
            item.id === id ? { ...item, ...data } : item
          ),
        })),

      updateQuantity: (id, quantity) =>
        set((state) => ({
          items: state.items.map((item) =>
            item.id === id ? { ...item, quantity: Math.max(1, quantity) } : item
          ),
        })),

      clearCart: () => set({ items: [] }),

      // Helpers for cross-selling
      getPrimaryLocationId: () => {
        const items = get().items;
        if (items.length === 0) return undefined;
        // Find the first item that has a location (Muthawif, etc)
        const itemWithLoc = items.find((i) => i.locationId);
        return itemWithLoc?.locationId;
      },

      getPrimaryDate: () => {
        const items = get().items;
        if (items.length === 0) return undefined;
        return items[0].scheduledStart;
      },

      getTotalIdr: () => {
        return get().items.reduce((total, item) => total + item.basePriceIdr * item.quantity, 0);
      },
    }),
    {
      name: "wifme-cart-storage",
      // Date objects need custom serialization for zustand persist.
      storage: createJSONStorage<CartState>(() => localStorage, {
        reviver: (key, value) => {
          if ((key === "scheduledStart" || key === "scheduledEnd") && typeof value === "string") {
            return new Date(value);
          }
          return value;
        },
      }),
    }
  )
);
