import type { ReactElement } from "react";
import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { CarFront, FileCheck2, Handshake, Plus, UserCheck } from "lucide-react";
import { Link } from "@/i18n/routing";
import { DataListPagination } from "@/components/shared/data-list-pagination";
import { DataListToolbar } from "@/components/shared/data-list-toolbar";
import { getServiceCategoryRows, type ServiceCategoryRow } from "@/lib/admin/data";
import { serviceTypeToKey } from "@/lib/admin/mappers";

export const metadata: Metadata = { title: "Kategori Layanan" };

const CATEGORY_ICONS = { muthawifPersonal: UserCheck, providerMuthawif: Handshake, transportation: CarFront, visaProcessing: FileCheck2, additionalServices: Plus } as const;
const PRICE_MODEL_LABELS = { CURRENCY: "IDR / SAR", B2B: "B2B", ROUTE: "Rute", DOCUMENT: "Dokumen", CUSTOM: "Kustom" } as const;

export default async function AdminServiceCategoriesPage(): Promise<ReactElement> {
  const t = await getTranslations("Admin.services");
  const list = await getTranslations("Admin.list");
  const categories = await getServiceCategoryRows();

  return <div className="flex flex-col gap-5 md:gap-6"><section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="hidden max-w-3xl md:block"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[var(--gold)]">{t("eyebrow")}</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-0.04em] text-[var(--charcoal)] md:text-3xl">{t("categoryPage.title")}</h1><p className="mt-3 text-sm font-medium leading-7 text-[var(--text-muted)]">{t("categoryPage.description")}</p></div><Link href="/admin/services/categories/new" className="inline-flex min-h-11 w-fit items-center justify-center gap-2 rounded-lg bg-[var(--emerald)] px-4 text-sm font-extrabold !text-white"><Plus className="size-4 text-white" aria-hidden="true" />{t("addCategory")}</Link></section><DataListToolbar searchLabel={list("search")} searchPlaceholder={list("searchPlaceholder")} filterLabel={list("filter")} sortLabel={list("sort")} actionLabel={list("apply")} filterName="status" filterOptions={[{ value: "", label: list("all") }, { value: "active", label: t("statuses.active") }, { value: "draft", label: t("statuses.draft") }]} sortOptions={[{ value: "order", label: t("fields.order") }, { value: "services", label: t("fields.services") }, { value: "latest", label: list("latest") }]} /><section className="overflow-hidden rounded-xl border border-[var(--border)] bg-white shadow-[0_10px_28px_rgba(22,33,28,0.05)]"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-[var(--ivory)] text-xs font-extrabold uppercase tracking-[0.12em] text-[var(--text-muted)]"><tr><th scope="col" className="px-5 py-4">{t("fields.order")}</th><th scope="col" className="px-5 py-4">{t("fields.category")}</th><th scope="col" className="px-5 py-4">{t("fields.services")}</th><th scope="col" className="px-5 py-4">{t("fields.priceModel")}</th><th scope="col" className="px-5 py-4">{list("status")}</th><th scope="col" className="px-5 py-4">{list("filter")}</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{categories.map((category) => <CategoryRow key={category.id} category={category} />)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{categories.map((category) => <CategoryCard key={category.id} category={category} />)}</div><DataListPagination label={list("page")} previousLabel={list("previous")} nextLabel={list("next")} /></section></div>;
}

async function CategoryRow({ category }: { readonly category: ServiceCategoryRow }): Promise<ReactElement> {
  const t = await getTranslations("Admin.services");
  const iconKey = serviceTypeToKey(category.serviceType);
  const Icon = CATEGORY_ICONS[iconKey];
  const status = category.status === "ACTIVE" ? "active" : "draft";
  return <tr><td className="px-5 py-4 font-extrabold text-[var(--charcoal)]">{category.order}</td><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-[var(--emerald-pale)] text-[var(--emerald)]"><Icon className="size-5" /></span><div><p className="font-extrabold text-[var(--charcoal)]">{category.title}</p><p className="text-xs font-bold text-[var(--text-muted)]">{category.description}</p></div></div></td><td className="px-5 py-4 font-extrabold text-[var(--charcoal)]">{category.serviceCount}</td><td className="px-5 py-4 font-bold text-[var(--text-muted)]">{PRICE_MODEL_LABELS[category.priceModel as keyof typeof PRICE_MODEL_LABELS]}</td><td className="px-5 py-4"><StatusPill label={t(`statuses.${status}`)} status={status} /></td><td className="px-5 py-4"><div className="flex gap-2"><Link href={`/admin/services/categories/${category.key}/edit`} className="inline-flex min-h-11 items-center rounded-lg border border-[var(--border)] px-4 font-extrabold text-[var(--charcoal)]">{t("actions.edit")}</Link><Link href={`/admin/services/categories/${category.key}/delete`} className="inline-flex min-h-11 items-center rounded-lg border border-[var(--border)] px-4 font-extrabold text-[var(--error)]">{t("actions.delete")}</Link></div></td></tr>;
}
async function CategoryCard({ category }: { readonly category: ServiceCategoryRow }): Promise<ReactElement> { const t = await getTranslations("Admin.services"); const Icon = CATEGORY_ICONS[serviceTypeToKey(category.serviceType)]; const status = category.status === "ACTIVE" ? "active" : "draft"; return <article className="rounded-xl border border-[var(--border)] bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-[var(--emerald)]/10 text-[var(--emerald)]"><Icon className="size-5" /></span><div className="min-w-0 flex-1"><h2 className="font-extrabold text-[var(--charcoal)]">{category.title}</h2><p className="mt-0.5 text-xs leading-5 text-[var(--text-muted)]">{category.description}</p></div><StatusPill label={t(`statuses.${status}`)} status={status} /></div><div className="mt-4 flex items-end justify-between gap-4"><div className="flex flex-wrap gap-x-4 gap-y-2 text-xs"><div><p className="font-bold text-[var(--text-muted)]">{t("fields.services")}</p><p className="mt-0.5 font-extrabold text-[var(--charcoal)]">{category.serviceCount}</p></div><div><p className="font-bold text-[var(--text-muted)]">{t("fields.providers")}</p><p className="mt-0.5 font-extrabold text-[var(--charcoal)]">{category.providerCount}</p></div></div><div className="flex gap-2"><Link href={`/admin/services/categories/${category.key}/edit`} className="inline-flex min-h-9 items-center rounded-lg border border-[var(--border)] bg-white px-3 text-xs font-extrabold text-[var(--charcoal)]">{t("actions.edit")}</Link><Link href={`/admin/services/categories/${category.key}/delete`} className="inline-flex min-h-9 items-center rounded-lg border border-[var(--border)] bg-white px-3 text-xs font-extrabold text-[var(--error)]">{t("actions.delete")}</Link></div></div></article>; }
function StatusPill({ label, status }: { readonly label: string; readonly status: string }): ReactElement { 
  let colors = "bg-[var(--emerald)]/10 text-[var(--emerald)]";
  if (status === "draft") colors = "bg-[var(--gold)]/10 text-[var(--gold)]";
  return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-extrabold ${colors}`}>{label}</span>; 
}
